services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: vegardit/graalvm-maven:17.0.8
    container_name: combine-dev
    init: true
    volumes:
      - type: bind
        source: ${COMBINE_REPO}
        target: /combine

