micronaut:
  application:
    name: Threshr
  http:
    services:
      redsky-api:
        url: https://redsky.target.com/
        path: redsky_aggregations/v1/web
---
threshr:
  key:
  channel:
  test:
    data:
      stores: ${TEST_DATA_STORES:nearby_stores.json}
      categories:  ${TEST_DATA_CATEGORIES:target_categories.txt}