micronaut:
  application:
    name: Threshr
  http:
    services:
      redsky-api:
        url: https://redsky.target.com/
        path: redsky_aggregations/v1/web
---
threshr:
  key:
  channel:
---
test:
  datasources:
    default:
      dialect:
      driverClassName:
      url:
      username:
    file:
      stores: ${:nearby_stores.json}
      categories: ${:target_categories.txt}