micronaut:
  application:
    name: Threshr
  http:
    services:
      redsky-api:
        url: https://redsky.target.com/
        path: redsky_aggregations/v1/web
---
threshr:
  key: ""
  CHANNEL: WEB
---
datasources:
  default:
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES
    schema-generate: NONE
    url: db.fmihonrcefvjcxcntqfx.supabase.co
    username: postgres
    password: ""
---
jpa:
  default:
    entity-scan:
      packages: com.github.graqr.threshr.model.silo
---
flyway:
  datasources:
    default:
      enabled: true
---
test-resource:
  pdp-client: file:pdp_client.json