micronaut:
  application:
    name: Threshr
  http:
    services:
      redsky-api:
        url: https://redsky.target.com/
        path: redsky_aggregations/v1/web
---
threshr:
  key:
  channel:
---
#datasources:
#  default:
#    driver-class-name: org.postgresql.Driver
#    db-type: postgres
#    schema-generate: CREATE_DROP
#    dialect: POSTGRES
#---
#jpa:
#  default:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: none
#          dialect: POSTGRES
#          db-type: postgres
#          driver-class-name: org.postgresql.Driver
#          username: 'sa'
#          password: ''