micronaut:
  application:
    name: Threshr
  http:
    services:
      redsky-api:
        url: https://redsky.target.com/
        path: redsky_aggregations/v1/web
---
threshr:
  key: ""
  CHANNEL: WEB
---
datasources:
  default:
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES
    schema-generate: NONE
    url: jdbc:postgresql://db.fmihonrcefvjcxcntqfx.supabase.co:5432/
    username: postgres
    password: 9DhCghHM1Ltr6bWU
---
flyway:
  datasources:
    default:
      enabled: true
---
test-resource:
  pdp-client: file:pdp_client.json