name: Feature Request
description: I have an idea! 
labels: [enhancement]
assignees: "Jonathan-Zollinger"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: summary
    attributes:
      label: Summary 
      description: Summarize the what you want to see enabled in terms of an action. 
      placeholder: I want to look right or left without turning my whole torso
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: What solution do you recommend?
      placeholder: Place all the baddies I'm fighting directly in front of me.
    validations:
      required: true
  - type: textarea
    id: explored-alternatives 
    attributes:
      label: Alternative
      description: What alternative solutions have you considered?
      placeholder: |
        I thought about getting a new bat suit where the neck could move freely, but I like my cowl as it is.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: I'm Batman.
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it.
      options:
        - label: I agree to follow this project's [Code of Conduct](../../CODE_OF_CONDUCT.md)
          required: true
  - type: markdown
    attributes:
      value: |
        <marquee>Thanks for filling out the feature request!</marquee>
