CREATE TABLE public.test_target_response_objects (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	response_body json NOT NULL,
	endpoint text NOT NULL,
	CONSTRAINT test_target_response_objects_pkey PRIMARY KEY (id)
);