micronaut:
  application:
    name: harvester
---
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES
---
threshr:
  key:
  channel:
---
jobrunr:
  background-job-server:
    enabled: false
  dashboard:
    enabled: false
---
test:
  datasources:
    default:
      url: