name: Run Maven Tests

on:
  push:

jobs:
  test:
    env:
      THRESHR_KEY: ${{ vars.THRESHR_KEY }}
      THRESHR_CHANNEL: ${{ vars.THRESHR_CHANNEL }}

    environment: redsky api
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Package with Maven
      run: mvn -B test --file pom.xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    
