name: Run Maven Tests

on: [push, pull_request]

jobs:
  test:
    env:
      THRESHR_KEY: ${{ secrets.THRESHR_KEY }}
      THRESHR_CHANNEL: ${{ vars.THRESHR_CHANNEL }}
      TEST_DATASOURCES_DEFAULT_URL: ${{ secrets.TEST_DATASOURCES_DEFAULT_URL }}

    environment: redsky api
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/virtual-environments/issues/709
    - name: "󰆴 Free disk space"
      run: |
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo apt-get clean
        df -h
    - name: "  Checkout repository"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: "󰬷 Set up JDK 17"
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: "󰙨 test with maven"
      run: mvn -B test --file pom.xml jacoco:report
    - name: generate report
      run: mvn sonar:sonar -Pcoverage
